### ISSUE TITLE
Can I use this code?

### ISSUE THREAD

**Issue by alichtman** [denji/jetbrains-utility#4]
I noticed there was no license, but I wanted to use this in my backup tool, [shallow-backup](https://github.com/alichtman/shallow-backup).

Would you be willing to license this?

**Comment by alichtman** [comment]
nvm, I think I have another way I want to go about solving the problem.

**Comment by denji** [comment]
Yes, no problem you can use/modify this code as you want.
https://github.com/denji/jetbrains-utility/blob/master/LICENSE

**Comment by alichtman** [comment]
Thanks!
